### ISSUE TITLE
Unicode Encode Error

### ISSUE THREAD

**Issue by rloganiv** [qiangning/crowdaq-client#2]
I get an error when trying to upload files with unicode characters in them. Here is the full traceback:
```
Traceback (most recent call last):
  File "cli.py", line 269, in <module>
    cli()
  File "/home/rlogan/anaconda3/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/rlogan/anaconda3/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/rlogan/anaconda3/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/rlogan/anaconda3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/rlogan/anaconda3/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/rlogan/anaconda3/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "cli.py", line 152, in _create
    resources.update(resource_id, resource_def)
  File "/home/rlogan/projects/crowdaq-client/client.py", line 52, in update
    headers=self.client.auth_headers)
  File "/home/rlogan/anaconda3/lib/python3.7/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/rlogan/anaconda3/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/rlogan/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/rlogan/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/rlogan/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/rlogan/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/rlogan/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/rlogan/anaconda3/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/rlogan/anaconda3/lib/python3.7/http/client.py", line 1289, in _send_request
    body = _encode(body, 'body')
  File "/home/rlogan/anaconda3/lib/python3.7/http/client.py", line 170, in _encode
    (name.title(), data[err.start:err.end], name)) from None
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2019' in position 350: Body ('’') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.
```

**Comment by qiangning** [comment]
Thanks. This is fixed in our repo now. We have everything hosted in another private repo and this is only the client repo that we've automatically pushed.
